### ISSUE TITLE
Lib-only installation

### ISSUE THREAD

**Issue by azukaar** [hazae41/mc-kutils#11]
Is it possible to install the lib with the additional functions like listen, without installing the whole process/embedded kotlin lib?
Thanks

**Comment by hazae41** [comment]
Just make a fork
Remove the kotlin lib from [build.gradle](https://github.com/hazae41/mc-kotlin/blob/2df81e28bba3331094cce7522ac00d51a92f590e/build.gradle#L15)
And grab the lib from jitpack:
https://jitpack.io/#azukaar/mc-kotlin

**Comment by azukaar** [comment]
Thanks!
